---
# Default GitHub labels
- color: c13253
  name: bug
  description: Functionality that does not work as intended/expected
- color: 18377f
  name: documentation
  description:
- color: 0366d6
  name: dependencies
  description: Pull requests that update a dependency file
- color: cccccc
  name: duplicate
  description: This issue or pull request already exists
- color: d29a5a
  name: test
  description:
- color: d23a4a
  name: automation
  description: Changes done to the .github folder
- color: blocked
  name: ed848a
  description: The issue is blocked by another issue that has to be resolved first
- color: 8fe57b
  name: feature request
  description: Functionality that introduces a new feature
- color: bbf796
  name: good first issue
  description: Good for newcomers
- color: f9bbc0
  name: help wanted
  description: We are looking for community help
- color: e6e6e6
  name: invalid
  description: The issue is not a valid bug/feature request
- color: ffffff
  name: wontfix
  description: The issue is expected and will not be fixed
- color: ef404d
  name: PSD
  description: Testing this works across all repos?
