name: Feature Request
description: File a feature request
title: "[Feat]: "
labels: [enhancement]
assignees:
  - palebludot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What feature would you like?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A new feature happened!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONTACT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
